pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    // Baixa o JDK 25 automaticamente se nao houver um na maquina (toolchain do build.gradle)
    id "org.gradle.toolchains.foojay-resolver-convention" version "1.0.0"
}

rootProject.name = 'intoxicantes'
